version: '3.9'
services:
  bot:
    build: .
    ports:
      - "3099:3099"
  redis:
    image: "redis:alpine"
  lavalink:
    restart: always
    image: fredboat/lavalink:master
    volumes:
      - type: bind
        source: /var/lavalink/application.yml
        target: /opt/Lavalink/application.yml